### ISSUE TITLE
refactor algorithms and move writes to DAO

### ISSUE THREAD

**Issue by jamesvclements** [st-thomas-more/stm-server#13]
- a lot of the algorithm logic could be done in a few lines with map and map reduce
- the file writes in the algorithms that mock writing to the database should be removed and replaced with a call to the `dao` that performs the write

**Comment by acmccuaig** [comment]
Need to fix calculation of Iowa score to be percentage not decimal in sixth algorithm

**Comment by jamesvclements** [comment]
created branch 13-refactor-algs to work on this
