### ISSUE TITLE
Add file upload functionality

### ISSUE THREAD

**Issue by jamesvclements** [st-thomas-more/stm-server#29]
Add functionality to a new subfolder of the `services` directory
Add a new endpoint in the `api` folder

**Comment by taylorjbrown** [comment]
PR made on teachDAO. The html file needs to be rendered from the stm-dashboard.
The html file is located in the src folder, the page is called "uploadCSV.html". We cannot write to the front-end repository so this will have to be done by the front-end team.

**Comment by jamesvclements** [comment]
Resolved in newDB
