### ISSUE TITLE
establish placements endpoint with daos

### ISSUE THREAD

**Issue by jamesvclements** [st-thomas-more/stm-server#9]
Create an endpoint for placements:

GET `/placements/{grade}?option=run` - get the placement for a specific grade. 
- grade is a path parameter

POST `/placements/{grade}` - runs the placement algorithm for a specific grade

PUT `/placements/{grade}` - update the placement for a specific grade. Pass in placement object.

DELETE `/placements/{grade}` - remove the placement for a specific grade.
Placement JSON object looks like: 
<img width="404" alt="screen shot 2016-10-22 at 3 38 29 pm" src="https://cloud.githubusercontent.com/assets/20052710/19622019/a5bbc72a-986d-11e6-90a2-7256f6a04fc0.png">

add mock daos

**Comment by andrew-wagner89** [comment]
created branch 9-placement-endpoints to work on this
